# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'
    additionalArguments: '/output json'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'printenv | sort'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    buildProperties: '/p:Version=$(GITVERSION.SEMVER) /p:AssemblyVersion=$(GITVERSION.ASSEMBLYSEMVER) /p:AssemblyInformationalVersion=$(GITVERSION.INFORMATIONALVERSION)'
    verbosityPack: 'Normal'
- task: CopyFiles@2
  inputs:
    contents: '**/*.nupkg'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop